In [11]:
#Install Required Packages
import numpy as np

In [35]:
"""
a_matrix is the coefficient matrix. b_matrix is the constants vector
"""
def gauss_elimination(a_matrix, b_matrix):
    # Validate that a_matrix is entered correctly
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Error: Coefficients matrix must be a square matrix!")
        return;

    # Validate b_matrix
    if b_matrix.shape[1] > 1 or b_matrix.shape[0] != a_matrix.shape[0]:
        print("Error: Constant vector incorrectly sized")
        return;


    # Initialisation of necessary variables
    n = len(b_matrix)
    m = n - 1
    i = 0;
    x = np.zeros(n)
    new_line = "\n"
    
    # Create the augmented matrix using Numpy's Concatenation feature
    augmented_matrix = np.concatenate((a_matrix, b_matrix), axis=1, dtype=float)
    print(f"The initial augmented matrix is : {new_line}{augmented_matrix}")
    print("Solving for the upper-triangular matrix")

    # Applying the Gaussian Elimination
    while i < n:
        if augmented_matrix[i][i] == 0.0: # Fail-safe to eliminate division by zero error
            print("Divide by zero error")
            return;

        for j in range(i + 1, n):
            scaling_factor = augmented_matrix[j][i] / augmented_matrix[i][i]
            print(scaling_factor)
            augmented_matrix[j] = augmented_matrix[j] - (scaling_factor * augmented_matrix[i])
            print(augmented_matrix)
        i = i + 1;
    print(augmented_matrix)
    # Backward substitution
    for k in range(n-1, -1, -1):
        x[k] = augmented_matrix[k][n]

        for j in range(k + 1, n):
            x[k] = x[k] -  x[j] * augmented_matrix[k][j]
        x[k] = x[k]/augmented_matrix[k][k]
           

    # Display result
    print(f"The following x-vector solves the above augmented matrix:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")
    

In [89]:
"""
a_matrix is the coefficient matrix. b_matrix is the constants vector
"""
def gauss_jordan_elimination(a_matrix, b_matrix):
    # Validate that a_matrix is entered correctly
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Error: Coefficients matrix must be a square matrix!")
        return;

    # Validate b_matrix
    if b_matrix.shape[1] > 1 or b_matrix.shape[0] != a_matrix.shape[0]:
        print("Error: Constant vector incorrectly sized")
        return;


    # Initialisation of necessary variables
    n = len(b_matrix)
    m = n - 1
    i = 0;
    x = np.zeros(n)
    new_line = "\n"
    
    # Create the augmented matrix using Numpy's Concatenation feature
    augmented_matrix = np.concatenate((a_matrix, b_matrix), axis=1, dtype=float)
    print(f"The initial augmented matrix is : {new_line}{augmented_matrix}")
    print("Solving for the upper-triangular matrix")

    # Applying the Gaussian Elimination
    while i < n:
        if augmented_matrix[i][i] == 0.0: # Fail-safe to eliminate division by zero error
            print("Divide by zero error")
            return;

        for j in range(i + 1, n):
            scaling_factor = augmented_matrix[j][i] / augmented_matrix[i][i]
            augmented_matrix[j] = augmented_matrix[j] - (scaling_factor * augmented_matrix[i])
            print(augmented_matrix)
        i = i + 1;

    # Normalize the diagonals
    for i in range(n):
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i][i]

    print(augmented_matrix)
    # Backward substitution
    for k in range(n-1, -1, -1):
        x[k] = augmented_matrix[k][n]
        for j in range(k + 1, n):
            x[k] = x[k] -  x[j] * augmented_matrix[k][j]

    # Display result
    print(f"The following x-vector solves the above augmented matrix:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")
    

In [19]:
"""
Added partial pivoting
a_matrix is the coefficient matrix. b_matrix is the constants vector
"""
def gauss_elimination_partial_pivoting(a_matrix, b_matrix):
    # Validate that a_matrix is entered correctly
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Error: Coefficients matrix must be a square matrix!")
        return;

    # Validate b_matrix
    if b_matrix.shape[1] > 1 or b_matrix.shape[0] != a_matrix.shape[0]:
        print("Error: Constant vector incorrectly sized")
        return;


    # Initialisation of necessary variables
    n = len(b_matrix)
    m = n - 1
    i = 0;
    x = np.zeros(n)
    new_line = "\n"
    
    # Create the augmented matrix using Numpy's Concatenation feature
    augmented_matrix = np.concatenate((a_matrix, b_matrix), axis=1, dtype=float)
    print(f"The initial augmented matrix is : {new_line}{augmented_matrix}")
    print("Solving for the upper-triangular matrix")

    # Applying the Gaussian Elimination
    while i < n:
        # Partial Pivoting
        for j in range(i+1, n):
            if abs(augmented_matrix[i, i]) < abs(augmented_matrix[j, i]):
                augmented_matrix[[j,i]] = augmented_matrix[[i,j]]
        
        if augmented_matrix[i][i] == 0.0: # Fail-safe to eliminate division by zero error
            print("Divide by zero error")
            return;

        for j in range(i + 1, n):
            scaling_factor = augmented_matrix[j][i] / augmented_matrix[i][i]
            print(scaling_factor)
            augmented_matrix[j] = augmented_matrix[j] - (scaling_factor * augmented_matrix[i])
            print(augmented_matrix)
        i = i + 1;

    # Backward substitution
    for k in range(n-1, -1, -1):
        x[k] = augmented_matrix[k][n]

        for j in range(k + 1, n):
            x[k] = x[k] -  x[j] * augmented_matrix[k][j]
        x[k] = x[k]/augmented_matrix[k][k]
           

    # Display result
    print(f"The following x-vector solves the above augmented matrix:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")
    

In [37]:
try: 
    variable_matrix = np.array([[1, 0, 1], [0, -3, 1], [2, 1, 3]])
    constant_matrix = np.array([[6], [7], [15]])
    gauss_elimination(variable_matrix, constant_matrix)
except ValueError:
    print("Please review the rows in your coefficient matrix")
except:
    print("An error occurred")

The initial augmented matrix is : 
[[ 1.  0.  1.  6.]
 [ 0. -3.  1.  7.]
 [ 2.  1.  3. 15.]]
Solving for the upper-triangular matrix
0.0
[[ 1.  0.  1.  6.]
 [ 0. -3.  1.  7.]
 [ 2.  1.  3. 15.]]
2.0
[[ 1.  0.  1.  6.]
 [ 0. -3.  1.  7.]
 [ 0.  1.  1.  3.]]
-0.3333333333333333
[[ 1.          0.          1.          6.        ]
 [ 0.         -3.          1.          7.        ]
 [ 0.          0.          1.33333333  5.33333333]]
[[ 1.          0.          1.          6.        ]
 [ 0.         -3.          1.          7.        ]
 [ 0.          0.          1.33333333  5.33333333]]
The following x-vector solves the above augmented matrix:
x0 is 2.0
x1 is -1.0
x2 is 4.0


In [15]:
X_matrix = np.array([[2, 3], [4, 9]])
y_vector = np.array([[4], [6]])
print(gauss_elimination(X_matrix, y_vector))

The initial augmented matrix is : 
[[2. 3. 4.]
 [4. 9. 6.]]
Solving for the upper-triangular matrix
2.0
[[ 2.  3.  4.]
 [ 0.  3. -2.]]
The following x-vector solves the above augmented matrix:
x0 is 3.0
x1 is -0.6666666666666666
None


In [21]:
X_matrix = np.array([[0, 2], [7, 9]])
y_vector = np.array([[6], [2]])
print(gauss_elimination_partial_pivoting(X_matrix, y_vector))

The initial augmented matrix is : 
[[0. 2. 6.]
 [7. 9. 2.]]
Solving for the upper-triangular matrix
0.0
[[7. 9. 2.]
 [0. 2. 6.]]
The following x-vector solves the above augmented matrix:
x0 is -3.5714285714285716
x1 is 3.0
None
