In [1]:
import numpy as np

In [2]:
def isDiagonalDominantMatrix(a_matrix):
    # Check that a square matrix is provided
    n = len(a_matrix)
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Coefficient matrix is not a square matrix")
        return False
    else:
        atleast_one = False
        for i in range(n):
            running_sum = 0
            for j in range(n):
                if i == j:
                    running_sum += abs(a_matrix[i][j])
                else:
                    running_sum -= abs(a_matrix[i][j])
            if running_sum < 0:
                return False
            if running_sum > 0:
                atleast_one = True
        return atleast_one
a = np.array([[9, 2, 3], [1, 12, 9], [4, 6, 14]])
b = np.array([[9, 2, 3], [1, 9, 9], [4, 6, 14]])
c = np.array([[9, 6, 3], [1, 9, 8], [4, 10, -15]])
print(isDiagonalDominantMatrix(a))
print(isDiagonalDominantMatrix(b))
print(isDiagonalDominantMatrix(c))

True
False
True


In [3]:
def jacobi_seidel(coefficient_matrix, constant_vector, tol):
    coefficient_matrix = coefficient_matrix.astype(np.float64)
    constant_vector = constant_vector.astype(np.float64)
    if not isDiagonalDominantMatrix(coefficient_matrix):
        return
    
    # Check that the length of the constant vector is equal to the length of the coefficient matrix
    if len(coefficient_matrix) != len(constant_vector):
        print("Matrices do not have the right dimension")
        return

    error = 10000
    n = len(constant_vector)
    x = np.zeros(n)
   
    while error > tol:
        for i in range(n):
            tracker = constant_vector[i];
            for j in range(n):
                if i != j:
                    tracker -= x[j]*coefficient_matrix[i][j]
            previous_res = x[i]
            x[i] = tracker/coefficient_matrix[i][i]
            error = abs(previous_res - x[i])
        print(x)
    print(f"The following x-vector solves the simultaneous equations:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")

In [4]:
a = np.array([[9, 2, 3], [1, 12, 9], [4, 6, 14]])
b = np.array([7, 2, 1])
jacobi_seidel(a, b, 0.000001)

[ 0.77777778  0.10185185 -0.19444444]
[ 0.81995885  0.2441701  -0.26748971]
[ 0.81268099  0.29956053 -0.28914908]
[ 0.8075918   0.31622916 -0.29483873]
[ 0.80578421  0.32064703 -0.29621564]
[ 0.80526143  0.32172328 -0.29652753]
[ 0.80512623  0.32196846 -0.29659398]
[ 0.80509389  0.32202099 -0.29660725]
[ 0.80508664  0.32203155 -0.29660971]
[ 0.80508511  0.32203352 -0.29661011]
The following x-vector solves the simultaneous equations:
x0 is 0.8050851125471855
x1 is 0.32203351939119335
x2 is -0.2966101118954216
