In [1]:
import numpy as np

In [11]:
def isDiagonalDominantMatrix(a_matrix):
    # Check that a square matrix is provided
    n = len(a_matrix)
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Coefficient matrix is not a square matrix")
        return False
    else:
        atleast_one = False
        for i in range(n):
            running_sum = 0
            for j in range(n):
                if i == j:
                    running_sum += abs(a_matrix[i][j])
                else:
                    running_sum -= abs(a_matrix[i][j])
            if running_sum < 0:
                return False
            if running_sum > 0:
                atleast_one = True
        return atleast_one
a = np.array([[9, 2, 3], [1, 12, 9], [4, 6, 14]])
b = np.array([[9, 2, 3], [1, 9, 9], [4, 6, 14]])
c = np.array([[9, 6, 3], [1, 9, 8], [4, 10, -15]])
print(isDiagonalDominantMatrix(a))
print(isDiagonalDominantMatrix(b))
print(isDiagonalDominantMatrix(c))

True
False
True


In [47]:
def jacobi_iteration(coefficient_matrix, constant_vector, tol):
    coefficient_matrix = coefficient_matrix.astype(np.float64)
    constant_vector = constant_vector.astype(np.float64)
    if not isDiagonalDominantMatrix(coefficient_matrix):
        return
    
    # Check that the length of the constant vector is equal to the length of the coefficient matrix
    if len(coefficient_matrix) != len(constant_vector):
        print("Matrices do not have the right dimension")
        return

    error = 10000
    n = len(constant_vector)
    x = np.zeros(n)
   
    while error > tol:
        xn = np.zeros(n)
        for i in range(n):
            tracker = constant_vector[i];
            for j in range(n):
                if i != j:
                    tracker -= x[j]*coefficient_matrix[i][j]
            previous_res = x[i]
            xn[i] = tracker/coefficient_matrix[i][i]
            error = abs(xn[i] - x[i])
        x = xn
        print(x)
    print(f"The following x-vector solves the simultaneous equations:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")

In [51]:
a = np.array([[9, 2, 3], [1, 12, 9], [4, 6, 14]])
b = np.array([7, 2, 1])
jacobi_iteration(a, b, 0.000001)

[0.77777778 0.16666667 0.07142857]
[ 0.71693122  0.04828042 -0.22222222]
[ 0.84112287  0.27358907 -0.15410053]
[ 0.76834705  0.21214849 -0.2861447 ]
[ 0.82601524  0.31724627 -0.23901994]
[ 0.78695192  0.27709702 -0.30053847]
[ 0.81638015  0.32649119 -0.2721707 ]
[ 0.79594775  0.30276301 -0.3017477 ]
[ 0.81107967  0.32664846 -0.28574065]
[ 0.80043611  0.31338218 -0.30030068]
[ 0.80823752  0.32518916 -0.29157411]
[ 0.80270489  0.31799412 -0.29886322]
[ 0.80673349  0.32392201 -0.29419888]
[ 0.8038614   0.32008803 -0.29789043]
[ 0.80594391  0.32309604 -0.2954267 ]
[ 0.80445423  0.3210747  -0.29731085]
[ 0.80553146  0.32261195 -0.29601894]
[ 0.80475921  0.32155325 -0.29698554]
[ 0.80531668  0.32234255 -0.29631117]
[ 0.80491649  0.32179032 -0.29680872]
[ 0.80520506  0.32219683 -0.2964577 ]
[ 0.80499772  0.32190952 -0.29671437]
[ 0.80514712  0.3221193  -0.296532  ]
[ 0.80503971  0.32197007 -0.29666459]
[ 0.80511707  0.32207847 -0.29656995]
[ 0.80506143  0.32200104 -0.29663851]
[ 0.80510149  0

array([ 0.80508507,  0.32203435, -0.29660977])