In [1]:
import numpy as np

In [2]:
def luFactorization(a_matrix, b_vector):
    # Verify a_matrix is sized correctly
    if a_matrix.shape[0] != a_matrix.shape[1]:
        print("Square matrix not provided")
        return
    # Verify b_vector is sized correctly
    if b_vector.shape[1] > 1 or a_matrix.shape[0] != b_vector.shape[0]:
        print("B vector not properly sized")
        return

    a_matrix = a_matrix.astype(np.float64)
    b_vector = b_vector.astype(np.float64)
    # Initialize required variables
    n = len(a_matrix)
    i = 0
    c = np.zeros(n) # Modified constant vector
    x = np.zeros(n) # Result vector
    lower_diag = np.identity(n) # Lower diagonal matrix

    #  Update the upper diagonal and lower diagonal matrix during forward elimination
    while i < n:
        if a_matrix[i][i] == 0.0:
            print("Division by 0 error")
            return
        for j in range(i + 1, n):
            scaling_factor = a_matrix[j][i] / a_matrix[i][i]
            lower_diag[j][i] = scaling_factor
            a_matrix[j] = a_matrix[j] - a_matrix[i] * scaling_factor
        i = i + 1
    

    # Update the modified constant vector via forward substition
    c[0] = b_vector[0][0]
    for i in range(1, n):
        tracker = b_vector[i][0]
        for j in range(0, i):
            tracker -= c[j] * lower_diag[i][j]
        c[i] = tracker

    # Update the resuclt vector via backward substitution
    x[n - 1] = c[n -1]/a_matrix[n-1][n-1]
    for i in range(n-2, -1, -1):
        tracker = c[i]
        for j in range(n-1, i - 1, -1):
            tracker -= (a_matrix[i][j] * x[j])
        x[i] = tracker/a_matrix[i][i]

    print("The upper triangular matrix is :")
    print(a_matrix)
    print("\nThe lower triangular matrix is :")
    print(lower_diag)
    # Display result
    print("\n")
    print(f"The following x-vector solves the simultaneous equations:")
    for answer in range(n):
        print(f"x{answer} is {x[answer]}")

In [3]:
X_matrix = np.array([[2, 3], [4, 9]])
y_vector = np.array([[4], [6]])
luFactorization(X_matrix, y_vector)

The upper triangular matrix is :
[[2. 3.]
 [0. 3.]]

The lower triangular matrix is :
[[1. 0.]
 [2. 1.]]


The following x-vector solves the simultaneous equations:
x0 is 3.0
x1 is -0.6666666666666666


In [4]:
variable_matrix = np.array([[1, 0, 1], [0, -3, 1], [2, 1, 3]])
constant_matrix = np.array([[6], [7], [15]])
luFactorization(variable_matrix, constant_matrix)

The upper triangular matrix is :
[[ 1.          0.          1.        ]
 [ 0.         -3.          1.        ]
 [ 0.          0.          1.33333333]]

The lower triangular matrix is :
[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 2.         -0.33333333  1.        ]]


The following x-vector solves the simultaneous equations:
x0 is 2.0
x1 is -1.0
x2 is 4.0


In [5]:
variable_matrix = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
constant_matrix = np.array([[-7], [-4], [2]])
luFactorization(variable_matrix, constant_matrix)

The upper triangular matrix is :
[[ 3.          2.         -1.        ]
 [ 0.         -5.          5.        ]
 [ 0.          0.          7.66666667]]

The lower triangular matrix is :
[[ 1.          0.          0.        ]
 [ 2.          1.          0.        ]
 [ 0.33333333 -1.86666667  1.        ]]


The following x-vector solves the simultaneous equations:
x0 is -2.0
x1 is 1.0
x2 is 3.0


In [6]:
variable_matrix = np.array([[-6, -3, 3], [9, 1, -6], [3, 2, -7]])
constant_matrix = np.array([[-14], [5], [15]])
luFactorization(variable_matrix, constant_matrix)

The upper triangular matrix is :
[[-6.         -3.          3.        ]
 [ 0.         -3.5        -1.5       ]
 [ 0.          0.         -5.71428571]]

The lower triangular matrix is :
[[ 1.          0.          0.        ]
 [-1.5         1.          0.        ]
 [-0.5        -0.14285714  1.        ]]


The following x-vector solves the simultaneous equations:
x0 is -0.6666666666666666
x1 is 5.0
x2 is -1.0
